### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by kinsleykajiva** [elcobvg/svelte-autocomplete#12]
i have added this library to my project but ever since its been failing to load ever since. Here is the error message . 

[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
node_modules/svelte-autocomplete/src/index.html (1:0)
1: <svelte:window on:click="close()"  />
   ^
2: <div on:click="event.stopPropagation()" class="autocomplete">
3:   <input
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (/home/kinsley/WebstormProjects/node_modules/rollup/dist/shared/rollup.js:5265:30)
    at Module.error (/home/kinsley/WebstormProjects/node_modules/rollup/dist/shared/rollup.js:9835:16)
    at tryParse (/home/kinsley/WebstormProjects/node_modules/rollup/dist/shared/rollup.js:9716:23)
    at Module.setSource (/home/kinsley/WebstormProjects/node_modules/rollup/dist/shared/rollup.js:10142:19)
    at ModuleLoader.addModuleSource (/home/kinsley/WebstormProjects/node_modules/rollup/dist/shared/rollup.js:18312:20)
    at ModuleLoader.fetchModule (/home/kinsley/WebstormProjects/node_modules/rollup/dist/shared/rollup.js:18368:9)
    at async Promise.all (index 2)
    at ModuleLoader.fetchStaticDependencies (/home/kinsley/WebstormProjects/node_modules/rollup/dist/shared/rollup.js:18393:34)
    at async Promise.all (index 0)
    at ModuleLoader.fetchModule (/home/kinsley/WebstormProjects/node_modules/rollup/dist/shared/rollup.js:18370:9)

**Comment by elcobvg** [comment]
Hi, it's still written in Svelte 2, that's why you get the error. I haven't had the time yet to update to Svelte 3, sorry.
